"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

icon = os.path.join(os.path.dirname(__file__), "icon.icns")

APP = ['main.py']
DATA_FILES = ['icon.png', 'data.json']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': icon,
}

setup(
    name="Little Snakey",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
